---
title: "git_00"
author: "Sophia Castellon"
date: "Sept 12, 2024" 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,   
      And the mome raths outgrabe.   
      
      
“Beware the Jabberwock, my son!   
      
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

The way a crow   
Shook down on me   
The dust of snow   
From a hemlock tree   

Has given my heart   

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,   
      Shining with all his might:    
He did his very best to make    
      The billows smooth and bright —    
And this was odd, because it was    
      The middle of the night.   

The moon was shining sulkily,   
      Because she thought the sun    
Had got no business to be there    
      After the day was done —    
"It's very rude of him," she said,    
      "To come and spoil the fun."    

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->   

What direction does your sentence move: you belonging to the land or the land belonging to you.     

This is a question of the people and the state.     

What can or cannot be bought and sold, given and taken.   

A question and a statement.    

In what was called the United Order, there was no selling of crops, no personal gain that wasn’t within reach of the greater good. That was the idea.    

We look not at the things which are seen but the things which are not seen. Our afﬂiction which is but for a moment is attached to a far more exceeding and eternal weight.     

Feel this weight, even for a moment. Such is the eternal. The stopping of the clock.    

When one points behind the shape of one body, there ever is another there.     

Where is the line between yours and ours.     

Depends on whom you ask. Depends on where you stand.          

